cmake_minimum_required(VERSION 3.22.1)
project(pvnative C CXX)
include(FetchContent)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_PYTHON_WRAPPER OFF CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
FetchContent_Declare(apriltag GIT_REPOSITORY https://github.com/AprilRobotics/apriltag.git GIT_TAG v3.4.2)
FetchContent_MakeAvailable(apriltag)
add_library(pvnative SHARED apriltag_jni.cpp)
target_include_directories(pvnative PRIVATE ${apriltag_SOURCE_DIR})
target_link_libraries(pvnative apriltag log)
